// <auto-generated />
using System;
using ChatAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220811114440_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChatAPI.Models.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("chatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            id = 1,
                            body = "Prva poruka",
                            chatId = 1,
                            isDeleted = false,
                            username = "PrviKorisnik"
                        },
                        new
                        {
                            id = 2,
                            body = "Druga poruka",
                            chatId = 1,
                            isDeleted = false,
                            username = "DrugiKorisnik"
                        },
                        new
                        {
                            id = 3,
                            body = "Treca poruka",
                            chatId = 1,
                            isDeleted = false,
                            username = "TreciKorisnik"
                        },
                        new
                        {
                            id = 4,
                            body = "Cetvrta poruka",
                            chatId = 1,
                            isDeleted = false,
                            username = "Muharem"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
